language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - git clone http://github.com/zenovich/runkit.git runkit
  - cd runkit
  - phpize
  - ./configure
  - make
  - sudo make install
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - cd ..
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script:
  - ./vendor/bin/phpunit --coverage-text --configuration ./tests/phpunit.xml
notifications:
    email:
        - judgedim@gmail.com