language: php
php:
  - 5.3
before_script:
  - pear channel-discover pear.survivethedeepend.com
  - pear install http://pear.survivethedeepend.com/get/Mockery-0.8.0.tgz
  - phpenv rehash
  - git clone git://github.com/rusnak/mutagenesis.git genesis
  - pear install genesis/pear.xml
  - phpenv rehash
  - git clone http://github.com/zenovich/runkit.git runkit
  - cd runkit
  - phpize
  - ./configure
  - make
  - sudo make install
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - cd ..
script: phpunit --coverage-text --configuration ./tests/phpunit.xml
notifications:
    email:
        - alexx.rusnak@gmail.com